### ISSUE TITLE
FormLayout inside VerticalLayout changes its width depending on form-items number

### ISSUE THREAD

**Issue by denis-anisimov** [vaadin/vaadin-form-layout#103]
I'm not sure whether this is a `VerticalLayout`  issue or `FormLayout` .
Please move it in the proper repository if needed.

The original issue is : https://github.com/vaadin/flow/issues/4924.

Steps to reproduce:
- create a vertical layout: var layout = document.createElement('vaadin-vertical-layout');
- create a form layout: var formLayout = document.createElement('vaadin-form-layout');
- append form layout to vertical layout : layout.appendChild(formLayout);
- add two form items: 
  - var formItem1 = document.createElement('vaadin-form-item');
  - var field = document.createElement('vaadin-text-field');
  - formItem1.appendChild(field);
  - var lbl = document.createElement('label');
  - lbl.slot="label";
  - lbl.innerText="A"
  - formItem1.appendChild(lbl);
  - formLayout.appendChild(formItem1);
  - repeat the same for `formItem2`.
- check that the width of the resulting `formLayout`  is not `100%`.
- repeat the previous step with two more items.

The result is: the `formLayout` increases its width.

Depending on your browser window size the `formLayout` will increase its width one more time if you repeat adding two items one more time.

**Comment by tomivirkki** [comment]
Verified the issue, `<vaadin-form-layout>` behaves really strangely inside a `<vaadin-vertical-layout>` (at least when populated dynamically like in the description)

**Comment by sergetania** [comment]
For the record, a form layout does not need to be inside of a vertical layout to observe this problem. It can be inside of a simple div that has display set to flex.

**Comment by limonte** [comment]
As I understand correctly, here's the simplest use case: https://overjoyed-cowl.glitch.me/

![image](https://user-images.githubusercontent.com/6059356/51741294-31dd8200-209f-11e9-8cb5-fce786be9c97.png)

The second form-layout with 3 fields is wider than the first one with 2 fields. That's unexpected, I agree with that.

The reason for that behavior is that in form-layout we're calculating form-items' width based on percentage, e.g. `width: calc(49.95% - 0.75rem)`.

We're not going to change this behavior, so I will suggest two possible workarounds:

1. Add `align-items: stretch` to `vaadin-vertical-layout`: https://vast-flute.glitch.me/
2. Add `align-self: stretch` to `vaadin-form-layout`: https://mercury-modem.glitch.me

The default value for `align-items` in `vaadin-vertical-layout` is `flex-start`, I'm not entirely sure about reasons for that but changing that would be breaking change we'd like to avoid.

**Comment by limonte** [comment]
Good day @sergetania and apologies for the delayed reply.

Your case could be achieved with something like this: https://plastic-warrior.glitch.me/

As you can see from the code https://glitch.com/edit/#!/plastic-warrior?path=index.html:23:29 all three form-layouts are placed inside vertical-layout with defined width and `align-items: stretch`.

We implemented form-layout this way because of multiple internal requirements, introducing breaking changes at this moment might not be a good idea.

But if you have a proposal of a better implementation, please report it and we will be more than happy to consider it.

**Comment by sergetania** [comment]
Thank you for getting back to me @limonte . 
Of course, defining the width will help position the fields but when a page is populated dynamically it is sometimes difficult to define a fixed width. It is much easier to have fields with defined width (based on the field purpose) and then let the layout fit the content. At least that is how it worked in V7. It is a basic feature of any layout in V7 with undefined width. None of them increased the width as more fields are added. 

Back to your example. Honestly, I am a bit surprised that width actually works more like max-width. (Yes, most of my experience is in Java). The layout gets more narrow than the defined 1000px as the width of the browser window is being decreased.

**Comment by web-padawan** [comment]
Note: `width: fit-content` from the above example kinda makes sense, but is not the viable option for us, as it is not supported by IE11 and Edge: https://caniuse.com/#feat=intrinsic-width

We will re-iterate on the possible solution later this week.
