### ISSUE TITLE
Anchor with button

### ISSUE THREAD

**Issue by vlipovetskii** [vaadin/vaadin-form-layout#137]
I leverage the combination of anchor and button to implement download as proposed in https://vaadin.com/forum/thread/17010389/17303946

Download works perfectly. Unfortunately the button inside anchor doesn't respect the rules of FormLayout. The button inside anchor unlike regualr standalone button doesn't occupy the complete form item cell.  
Please find the screenshot
![anchorToDownloadWithButton-vs-button](https://user-images.githubusercontent.com/19362031/59127238-c15d4080-896f-11e9-832d-843c0cea66fd.png)
and the sample project https://github.com/vlipovetskii/vaadin-issue-0001-prj

**Comment by web-padawan** [comment]
Styling nested slotted elements with `::slotted() ` isn't supported, this is how CSS works with Shadow DOM. 

The only element which has a special meaning in `<vaadin-form-layout>` is `<hr>` element which creates line breaks.
As mentioned above, we are not going to introduce any other element-specific hacks to our layout components.

Closing as won't fix.
