### ISSUE TITLE
Weird behaviour when toggling visibility of components under it

### ISSUE THREAD

**Issue by syampillai** [vaadin/vaadin-form-layout#144]
Layout behaviour of FormLayout changes when we toggle the visibility of components under it.

An example Java code is given below. The "Test" button can be clicked to toggle the visibility of the first TextField.

Before Hiding:
![beforehiding](https://user-images.githubusercontent.com/4854045/41229459-1ec87492-6d8d-11e8-9d01-556aea939426.jpg)

After Hiding:
![afterhiding](https://user-images.githubusercontent.com/4854045/41229458-1ea0defa-6d8d-11e8-8e34-b274c5459361.jpg)

When the text field is made hidden, gaps between rest of the text fields disappear! Screen-shots are shown above.
```
public class TestFormLayout extends FormLayout {
        public TestFormLayout() {
            TextField tf = new TextField("One");
            add(new Button("Test", e -> tf.setVisible(!tf.isVisible())));
            add(tf);
            add(new TextField("Two"));
            add(new TextField("Three"));
            add(new TextField("Four"));
            add(new TextField("Five"));
            add(new TextField("Six"));
        }
    }
```

**Comment by web-padawan** [comment]
Fixed by #123 and works properly since Vaadin 14.2.
