### ISSUE TITLE
Form layout inside combo box problem

### ISSUE THREAD

**Issue by qvanphong** [vaadin/vaadin-form-layout#153]
Straight problem when I place my form layout inside combo box, the first time when I click on combo box to show its items, everything is fine, then if I retry, every items in combo box have a small space between each other.

here is the first time if I click:
![image](https://user-images.githubusercontent.com/39910970/115984859-5785c880-a5d3-11eb-823b-ac156cec3fb1.png)

But then if click again:
![image](https://user-images.githubusercontent.com/39910970/115984878-653b4e00-a5d3-11eb-924a-cdb82f78a8c8.png)

When this problem happen, try to scroll fast to bottom of items list, it will back to normal:

https://user-images.githubusercontent.com/39910970/115985109-7b95d980-a5d4-11eb-9b74-0d2442023e06.mp4

**Comment by qvanphong** [comment]
My java code:

`private ComponentRenderer<VerticalLayout, Datum> createDesktopDelegateListComboBox() {
        return new ComponentRenderer<>(delegate -> {
            String formattedWeight = String.format("%.2f", Long.parseLong(delegate.getDelegateStatistics().getVoting_power()) / 100000000F);

            Element subRanking = new Html("<sup style='color: var(--lumo-error-color)'>" + delegate.getRank() + "</sup>").getElement();
            Span delegateNameWithRank = new Span(delegate.getName());
            delegateNameWithRank.getElement().appendChild(subRanking);
            Span payout = new Span(String.valueOf(delegate.getPayout_percent()));
            Span voteWeight = new Span(formattedWeight);

            delegateNameWithRank.setId("content-s");
            payout.setId("content-s");
            voteWeight.setId("content-s");

            FormLayout formLayout = new FormLayout();
            formLayout.setResponsiveSteps(
                    new FormLayout.ResponsiveStep("0px", 1, FormLayout.ResponsiveStep.LabelsPosition.ASIDE),
                    new FormLayout.ResponsiveStep("550px", 3, FormLayout.ResponsiveStep.LabelsPosition.TOP));
            formLayout.addFormItem(delegateNameWithRank, "Name");
            formLayout.addFormItem(payout, "Shares");
            formLayout.addFormItem(voteWeight, "Vote weight");

            return new VerticalLayout(formLayout);
        });
    }
    
    public void init() {
        myCombobox.setRenderer(createDesktopDelegateListComboBox());
    }
    `

**Comment by qvanphong** [comment]
workaround: 
If I remove "new FormLayout.ResponsiveStep("550px", 3, FormLayout.ResponsiveStep.LabelsPosition.TOP)"

and become
 formLayout.setResponsiveSteps(new FormLayout.ResponsiveStep("0px", 3, FormLayout.ResponsiveStep.LabelsPosition.TOP));
 
Then the problem is gone.

**Comment by rolfsmeds** [comment]
Hi, the FormLayout component is not intended to be used inside the dropdown of a ComboBox. While it's technically possible to do, it's not a supported use case. I suggest creating a more lightweight html-based template to achieve the same item rendering.
