### ISSUE TITLE
Add example of integration with iron-form (sign-in form)

### ISSUE THREAD

**Issue by limonte** [vaadin/vaadin-form-layout#25]
It would be nice to have an example of `iron-form` inside `vaadin-form-layout`. 

The sign-in form should contain: 

 - `vaadin-text-field` element - username 
 - `vaadin-email-field` element - email 
 - `vaadin-password-field` element - password 
 - `vaadin-button` which is disabled by default and become enabled if all fields are valid
 - proper way to show validation errors without using `document.getElemtntById()` 

(This is the DX tests finding)

**Comment by web-padawan** [comment]
Polymer elements are in the maintenance mode now. So we are not going to use them in demos.
We have already removed `iron-form` from other components demos so I'm closing this issue.
