### ISSUE TITLE
Users are expecting more than layout from `vaadin-form-layout`

### ISSUE THREAD

**Issue by limonte** [vaadin/vaadin-form-layout#28]
Probably we should consider renaming the element or adding a well visible statement in docs that `vaadin-form-layout` is only about the layout, there's nothing about validation or object with fields' values, etc.

(This is the DX tests finding)

**Comment by jouni** [comment]
This is the situation for 1.0, and it is reflected in the name, right? Also, there have been vague plans about adding more form features to it in the future, like you mentioned, or generating a form out of a JS object automatically.

**Comment by limonte** [comment]
> This is the situation for 1.0, and it is reflected in the name, right? 

Rigth.

> Also, there have been vague plans about adding more form features to it in the future, like you mentioned, or generating a form out of a JS object automatically.

In that case, the `layout` part of the component name will be inaccurate :/

**Comment by jouni** [comment]
> In that case, the layout part of the component name will be inaccurate :/

Yeah, probably. But those plans are really vague at the moment, so I wouldn’t worry about it. We can introduce another element for those features if needed, and use this layout inside it.

**Comment by limonte** [comment]
Add a notification that it's only about the layout, nothing more than that.

**Comment by web-padawan** [comment]
The description at https://vaadin.com/components/vaadin-form-layout is probably enough.

> The Web Component providing configurable responsive layout for form elements. Part of the Vaadin components.

> Features
> Responsive
> Makes sure your form content stays easily readable on all devices.

Also the component is under "Layouts" block at https://vaadin.com/components.

So I'm closing this issue as outdated. The need for a form component can be discussed in other issues, and we have a place for it at https://github.com/vaadin/proposal-for-vaadin-form.
