### ISSUE TITLE
Add default basic styles: "pretty, but simple"

### ISSUE THREAD

**Issue by limonte** [vaadin/vaadin-form-layout#30]
Related Flowdock discussion: https://www.flowdock.com/app/vaadin/elements-team/threads/_PAcKU7U0EWmAm1stFTzwdmDo-Z

(This is the DX tests finding)

**Comment by jouni** [comment]
As discussed with @platosha, we think we should add a default margin for the form-item to provide a vertical gap, and that should be controlled with `--vaadin-form-item-row-gap`. This should satisfy the default styles.

**Comment by limonte** [comment]
That won't fix use cases w/o `vaadin-form-item`, e.g.:

- https://cdn-origin.vaadin.com/vaadin-form-layout/1.0.0-alpha2/demo/#vaadin-text-fields-as-form-items
- https://cdn-origin.vaadin.com/vaadin-form-layout/1.0.0-alpha2/demo/#paper-inputs-as-form-items

**Comment by jouni** [comment]
The example with paper-input is fine, right?

But for vaadin-text-field, it’s true, it won’t fix the issue, at least for now. We can either wrap the fields with form-items or add some CSS in the examples.

**Comment by limonte** [comment]
> The example with paper-input is fine, right?

Right.

> But for vaadin-text-field, it’s true, it won’t fix the issue, at least for now. We can either wrap the fields with form-items or add some CSS in the examples.

True that.
