### ISSUE TITLE
Responsive Layout

### ISSUE THREAD

**Issue by Saulis** [vaadin/vaadin-form-layout#4]
Specs by @jouni 

Depends on #5 (multiple columns), where “column count” is described.

Column count is reduced at certain breakpoints. The developer can configure those if needed using a property, e.g. `columns`.

The property value format is a comma-separated list of space-separated values of a CSS length and a number, where the CSS length indicates the breakpoint width and the number indicates the column count. The length value can be omitted which equals it to `0`.

The default value for that property is `1, 40em 2` (might change), which means the following:

When the layout width (independent of the browser viewport width) is:
- `< 40em` column count is 1.
- `>= 40em` column count is 2.

More examples:

- `columns="1"` column count is always 1
- `columns="3"` column count is always 3
- `columns="1 3"` column count is always 3
- `columns="3 1"` invalid length (`3` == `0`), column count is always 1
- `columns="1, 400px 2"` column count is 1 below 400px, and 2 above 400px
- `columns="1, 600px 2"` column count is 1 below 600px, and 2 otherwise
- `columns=""` any unrecognized value (including single length values like `123px`) is ignored and equals to `1`.

**Comment by jouni** [comment]
This is so closely related to #5 (multiple columns) it feels to me they should be done together.

**Comment by jouni** [comment]
At least I provided the designs for this in a comment in #5.

**Comment by jouni** [comment]
Updated the specs. The `--vaadin-form-layout-columns` property is probably controversial, so take some time to think about it.

**Comment by limonte** [comment]
https://picturepan2.github.io/spectre/layout.html

**Comment by tomivirkki** [comment]
We could consider dropping the number from the syntax and just leave the threshold values: 
- `columns='400px'` column count is 1 below 400px, and 2 above 400px
- `columns='400px 600px'` column count is 1 below 400px, and 2 above 400px, and 3 above 600px
