### ISSUE TITLE
API Change: labelsOnTop: boolean to labelsPosition: string

### ISSUE THREAD

**Issue by platosha** [vaadin/vaadin-form-layout#40]
As discussed with colleagues, `labelsOnTop` boolean flag is confusing and not future-compatible.

Let us change to `labelsPosition: <"top"|"aside">` string instead.

**Comment by limonte** [comment]
It's labelPosition, not label**s**Position.

**Comment by platosha** [comment]
There are multiple labels though.

**Comment by limonte** [comment]
Let's not discuss things which are already discussed. If you think that plural is better in this case, feel free to continue yesterday's conversation about this parameter on Flowdock.
