### ISSUE TITLE
Updating colspan at runtime has no effect

### ISSUE THREAD

**Issue by ripla** [vaadin/vaadin-form-layout#46]
*Steps to reproduce*
1. Open https://cdn-origin.vaadin.com/vaadin-form-layout/1.0.0/demo/#spanning-items-on-multiple-columns
2. Edit the address field to have `colspan="1"`

*Actual result*
Nothing happens

*Expected result*
The address field is rendered with the same width as the first name field

**Comment by platosha** [comment]
Confirmed.

As a workaround, you can trigger layout update manually by invoking `formLayout.updateStyles()` (documented API).
