### ISSUE TITLE
Match readme's code example with screenshot

### ISSUE THREAD

**Issue by samiheikki** [vaadin/vaadin-form-layout#50]
Would be much more clear if the code example and screenshot match in readme file.
<img width="935" alt="screen shot 2017-11-29 at 18 21 14" src="https://user-images.githubusercontent.com/8615573/33385806-31d30a32-d532-11e7-8c5d-5b9cf9a3eaf3.png">

**Comment by web-padawan** [comment]
Fixed in 4a6e0c5
