### ISSUE TITLE
Elements are vertically distorted in IE11

### ISSUE THREAD

**Issue by alexberazouski** [vaadin/vaadin-form-layout#51]
Following clean polymer example contains no custom styles:
```
    <vaadin-form-layout responsive-steps="[[_getResponsiveSteps(16)]]">
      <vaadin-combo-box colspan="3"></vaadin-combo-box>
      <vaadin-combo-box colspan="5"></vaadin-combo-box>
      <div colspan="4">div content</div>
      <vaadin-button colspan="2" id="order-item-edit-delete" >Button text
      </vaadin-button>
    </vaadin-form-layout>
...
      _getResponsiveSteps(cols) {
        return [{
          columns: cols,
          labelsPosition: 'top'
        }];
      }
```
displayed in IE11 as:
![screen shot 2017-11-30 at 11 07 35](https://user-images.githubusercontent.com/28781210/33422542-b7522648-d5be-11e7-9cea-a2756a0e1007.png)
in chrome it looks as expected:
![screen shot 2017-11-30 at 11 06 09](https://user-images.githubusercontent.com/28781210/33422651-11ca5f46-d5bf-11e7-9dc8-f7250252ab6d.png)

Different elements have different vertical alignment in IE: `div` and `button` are 
below the combobox.

Btw in bakery valo theme is used and some styles are applied
![screen shot 2017-11-30 at 11 15 34](https://user-images.githubusercontent.com/28781210/33422911-ec887050-d5bf-11e7-8026-0689a0bc82a9.png)
as a result: `vaadin-combobox` and `div` vertically are placed in the middle, `custom element` above and `vaadin-button` is below, but in chrome everything looks as expected.

Any suggestions how to place elements in one line in IE?

**Comment by jouni** [comment]
A jsfiddle/jsbin example would be great, speeds things up when trying to reproduce this.

I think the problem originates from the internal label element in the text-field element.

In Valo, there’s a ”magic number” that tries to align all the elements as expected on the same baseline, but that doesn’t yet work in IE11 (haven’t found the time to fix it yet): https://github.com/vaadin/vaadin-valo-theme/blob/master/vaadin-text-field.html#L10-L12

There’s also a test case for this: https://github.com/vaadin/vaadin-valo-theme/blob/master/test/vertical-alignment.html

Workarounds: 
- If the elements are inside the same linebox, then you should try to use `vertical-align` to align them
- If the elements are inside a flex container, use `align-items` and/or `align-self`

**Comment by jouni** [comment]
`vaadin-form-layout` uses flexbox, so `align-self` is probably the best workaround there.

**Comment by jouni** [comment]
The vertical alignment issues should now be fixed in the latest element themes. Please add a comment if you still experience this issue.
