### ISSUE TITLE
Element overflows body horizontally

### ISSUE THREAD

**Issue by samiheikki** [vaadin/vaadin-form-layout#52]
Live demo: https://plnkr.co/edit/ouVCNMrlRZcRLABrCyt1?p=preview

It overflows horizontally and creates scrollbars in the body.

**Comment by tomivirkki** [comment]
Agreed to assign the margins/overrides programmatically for selected nodes to avoid the issue. The child nodes are iterated anyway at https://github.com/vaadin/vaadin-form-layout/blob/master/src/vaadin-form-layout.html#L414 so this shouldn't cause additional overhead.
