### ISSUE TITLE
Noticeable jump form the default 100% state to the expected one (Edge)

### ISSUE THREAD

**Issue by tomivirkki** [vaadin/vaadin-form-layout#57]

**Comment by web-padawan** [comment]
Discussed in person. The reason for this to appear in the UX app is actually the [unresolved](https://www.polymer-project.org/2.0/docs/devguide/style-shadow-dom#style-undefined-elements) state, which obviously cannot be styled from the inside of the element itself. We would rather expect it to be handled by the user either by setting `unresolved` attribute on `body`or by delaying the registration until `WebComponentsReady`. So I'm closing this as won't fix.
