### ISSUE TITLE
If form layout child is invisible initially then form layout is not responsive

### ISSUE THREAD

**Issue by denis-anisimov** [vaadin/vaadin-form-layout#66]
This usecase includes dialog so may be it also somehow relates to the dialog.
I'm not sure. Please move it to the dialog repository if necessary.

I have two _almost identical_ templates:

```
<link rel="import" href="../bower_components/polymer/polymer-element.html">
<link rel="import" href="../bower_components/vaadin-form-layout/src/vaadin-form-layout.html">

<!-- Defines the example-template element -->
<dom-module id="example-template1">

    <template>

        <span>[[value]]</span>

        <vaadin-form-layout id="form1">
            <h3>Column 1</h3>
            <h3>Column 2</h3>
        </vaadin-form-layout>

    </template>

    <!-- Polymer boilerplate to register the example-template element -->
    <script>
        class ExampleTemplate1 extends Polymer.Element {
            static get is() {
                return 'example-template1'
            }

            ready() {
                super.ready();

                this.$.form1.responsiveSteps = [
                  {columns: 1, labelsPosition: 'top'},
                  {minWidth: '600px', columns: 2, labelsPosition: 'top'}
                ];
            }
        }
        customElements.define(ExampleTemplate1.is, ExampleTemplate1);
    </script>
</dom-module>
```

```
<link rel="import" href="../bower_components/polymer/polymer-element.html">
<link rel="import" href="../bower_components/vaadin-form-layout/src/vaadin-form-layout.html">

<!-- Defines the example-template element -->
<dom-module id="example-template2">

    <template>

        <span>[[value]]</span>

        <vaadin-form-layout id="form1" hidden="true">
            <h3>Column 1</h3>
            <h3>Column 2</h3>
        </vaadin-form-layout>

    </template>

    <!-- Polymer boilerplate to register the example-template element -->
    <script>
        class ExampleTemplate2 extends Polymer.Element {
            static get is() {
                return 'example-template2'
            }

            ready() {
                super.ready();

                this.$.form1.responsiveSteps = [
                  {columns: 1, labelsPosition: 'top'},
                  {minWidth: '600px', columns: 2, labelsPosition: 'top'}
                ];
            }
        }
        customElements.define(ExampleTemplate2.is, ExampleTemplate2);
    </script>
</dom-module>
```

The only difference is : the first template is visible initially, the content of the second template is hidden initially.

Now:
- create instances of those web components and add them into dialog
- see below the DOM structure of the dialog
- find the second template in the DOM 
- select the form layout in its shadow root and set `hidden` to false
- now both template are visible but the first template takes the whole horizontal space and the second one doesn't
- If both templates are not hidden initially then it doesn't happen: both takes all horizontal space

See image below how two templates looks after removing `hidden`.

This is how the dialog overlay look in the DOM
<img width="650" alt="screen shot 2018-02-26 at 3 20 58 pm" src="https://user-images.githubusercontent.com/11425472/36670225-ac92e1f4-1b08-11e8-9c89-8dd37b2b9804.png">

This is how the dialog looks like after  after removing `hidden`
<img width="1154" alt="screen shot 2018-02-26 at 3 24 33 pm" src="https://user-images.githubusercontent.com/11425472/36670382-2dc1943c-1b09-11e8-9207-bbfc0f0a066c.png">

Look at the style calculations :
<img width="678" alt="screen shot 2018-02-26 at 3 25 59 pm" src="https://user-images.githubusercontent.com/11425472/36670439-67ebae90-1b09-11e8-86c2-a27ed7b2b8f1.png">

If browser window size is changed (anyhow) then everything immediately shown as it should.

**Comment by manolo** [comment]
This should fix the problem https://github.com/vaadin/vaadin-overlay/issues/61 if the dialog was closed.

Otherwise if Flow developer decides to change the content of a dialog when it's open it needs to close/open the dialog, or notify manually to the dialog that content was changed somehow:
- Executing some update method in vaadin-form (there is no public one)
- Update the dialog somehow (no api also for this)
- Sending an `resize` event to window
Any of them can be implemented in `vaadin-dialog-flow`

**Comment by greenhost87** [comment]
For the record, if some one need that code that fire resize from server:

```java
UI.getCurrent().getPage().executeJavaScript("$0.notifyResize()", form.getElement());
```
