### ISSUE TITLE
Add `animation listener` workaround

### ISSUE THREAD

**Issue by manolo** [vaadin/vaadin-form-layout#73]
When hiding/displaying form layouts it should execute `notifyResize`, it can be performed by listening to `animationend` events

Take as reference, how the trick is used in grid https://github.com/vaadin/vaadin-grid/blob/2633e16f14df253a9673c0660c8d53a968d6adb9/src/vaadin-grid.html#L303

**Comment by web-padawan** [comment]
Workaround added in #90
