### ISSUE TITLE
Label

### ISSUE THREAD

**Issue by Saulis** [vaadin/vaadin-form-layout#9]
Current specs by @jouni

### Form layout item can be given a label

For situations where the field doesn’t have built-in support for the responsive label alignment (left-of-the-field by default, top-of-the-field after a breakpoint or opt-in), the developer can add a wrapper element around the field and provide a label element inside the wrapper.

This label is for visual purposes only at this point, so no accessibility bindings between the label and the field are made. We already prototyped this a bit, but we couldn’t find a nice way. That prototyping should be continued later.

**API proposal:**
```html
<vaadin-form-layout>
  <!-- 
    Providing a responsive label for a field which does not have built-in integration 
  -->
  <vaadin-form-item>
    <!-- 
      Slot for the responsive label. If the developer wants this to be announced by 
      the screen reader, they need to add that themselves.
    -->
    <label slot="label">Send newsletter</label>

    <!-- 
      Any elements without a named slot are placed inside the "field column" 
    -->
    <label><input type="radio" name="newsletter"> Daily</label>
    <label><input type="radio" name="newsletter"> Weekly</label>
    <label><input type="radio" name="newsletter"> Monthly</label>
    <label><input type="radio" name="newsletter"> Never</label>
  </vaadin-form-item>

  <!-- 
    Text field takes the entire column width. Label behaviour is default — on top, floating in Material theme
  -->
  <vaadin-text-field label="Name"></vaadin-text-field>
</vaadin-form-layout>
```

### The position and size/width of the label are controlled by the form layout

By default, the label is placed on the left side of the field (or right side for RTL languages). On certain breakpoints the labels should be on top of the field. The breakpoints that wrap the label on top are specified in the `columns` property (see #4) with a keyword, for example:

```html
<vaadin-form-layout columns="1 labels-on-top, 20em 1, 40em 2 labels-on-top, 60em 2">
  ...
</vaadin-form-layout>
```

Meaning:
- \>= 0: 1 column, labels on top
- \>= 20em: 1 column, labels aside
- \>= 40em: 2 columns, labels on top
- \>= 60em: 2 columns, labels aside

(APIs can change)

The “label column” width is controlled by the form-layout, and it can be a “fixed” width at this point and not affected by the length of the labels.

The width can be controlled with a CSS custom property (e.g. `--vaadin-form-item-label-width`). The default width is `8em`.

The gap between the label and the field can be controlled with a CSS custom property (e.g. `--vaadin-form-item-label-gap`). The default gap is `1em`.

**Comment by jouni** [comment]
Updated the specs in the description. Please take a look and comment!

**Comment by Saulis** [comment]
LGTM :+1:

**Comment by jouni** [comment]
Added specs for the label gap and the default width of the form item.
